name: Release build

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      DIST_DIR: yt-dlp-linux-${{ matrix.suffix }}

    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            suffix: x64
          - os: ubuntu-22.04-arm
            suffix: arm64

    steps:
      - uses: actions/checkout@v4

      - run: cargo build --release

      - run: |
          mkdir "$DIST_DIR"
          cp target/release/yt-dlp-api "$DIST_DIR/"
          cp config.example.toml "$DIST_DIR/"
          cp README.md "$DIST_DIR/"
          tar czf "$DIST_DIR.tar.gz" "$DIST_DIR"

      - uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: ${{ env.DIST_DIR }}.tar.gz
